version: '3'

services:
  web:
    image: web_image
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    env_file:
      environment/local
    ports:
      - 8080:8080
    depends_on:
      - celery
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
  tests:
    build:
      dockerfile: Dockerfile-test
      context: .
    command: bash -c "prospector && coverage run --source='.' manage.py test ${TEST_ARGS} --noinput -v 1 && coverage report"
    volumes:
      - .:/app
    env_file:
      environment/local
    depends_on:
       - db
       - firefox
  selenium-hub:
    image: selenium/hub:3.141.59-selenium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox:3.141.59-selenium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    env_file:
      environment/local
  celery:
    image: web_image
    working_dir: /app
    command: bash -c "rm -f celeryd.pid celerybeat-schedule celerybeat.pid && celery -A core worker -l info --detach && celery -A core beat --detach && celery flower -A core --address=0.0.0.0 --port=8888"
    ports:
      - 8888:8888
    volumes:
      - .:/app
    env_file:
      environment/local
    depends_on:
      - rabbitmq
