# Generated by Django 2.2.4 on 2019-11-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_auto_20191107_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='judgment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='judgment_inform',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='judgment_misleading_item',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='judgment_reduce',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='judgment_remove',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='predict_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='predict_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='predict_c',
            field=models.IntegerField(default=0),
        ),
    ]
