# Generated by Django 2.2.4 on 2019-11-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20191107_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='judgment',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
