# Generated by Django 2.2.4 on 2019-11-09 16:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_auto_20191108_1042'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='evidence',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='judgment_inform',
            field=models.BooleanField(choices=[(True, 'Yes, platforms should inform users that the item may be misleading.'), (False, 'No, platforms should not inform users that the item may be misleading.')], default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='judgment_misleading_item',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='judgment_reduce',
            field=models.BooleanField(choices=[(True, 'Yes, platforms should reduce exposure to the item.'), (False, 'No, platforms should not reduce exposure to the item.')], default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='judgment_remove',
            field=models.BooleanField(choices=[(True, 'Yes, platforms should remove the item.'), (False, 'No, platforms should not remove the item.')], default=False),
        ),
        migrations.AlterField(
            model_name='rater',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rater',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='f', max_length=255),
        ),
    ]
