# Generated by Django 2.2.4 on 2019-11-09 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20191109_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
