# Generated by Django 2.2.4 on 2019-12-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_auto_20191109_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='qualification',
            field=models.CharField(choices=[('1', 'Qualification 1'), ('2', 'Qualification 2'), ('3', 'Qualification 3')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
