# Generated by Django 2.2.4 on 2019-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_auto_20191202_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorroboratingChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationanswer',
            name='corroborating_link',
        ),
        migrations.AddField(
            model_name='registrationanswer',
            name='corroborating_link',
            field=models.ManyToManyField(to='workflow.CorroboratingChoices', verbose_name='Which of the following are you supposed to enter in the field for a corroborating link?'),
        ),
    ]
