# Generated by Django 2.2.4 on 2019-12-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_auto_20191202_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationanswer',
            name='pay_attention_to_others_on_judgment',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Not sure')], max_length=1, verbose_name='In the “Judgments” section of the form, should you take into account what you think other labelers are likely tosay about an item?'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='pay_attention_to_others_on_prediction',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Not sure')], max_length=1, verbose_name='In the “Predictions” section of the form, should you take into account what you think other labelers are likely to say about an item?'),
        ),
    ]
