# Generated by Django 2.2.4 on 2019-12-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_auto_20191202_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_start', models.DateTimeField()),
                ('answer_end', models.DateTimeField()),
                ('evidence', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('evidence_url', models.URLField(blank=True, null=True)),
                ('judgment', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('judgment_misleading_item', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default=1, max_length=1)),
                ('judgment_remove', models.BooleanField(choices=[(True, 'Yes, platforms should remove the item.'), (False, 'No, platforms should not remove the item.')], default=False)),
                ('judgment_reduce', models.BooleanField(choices=[(True, 'Yes, platforms should reduce exposure to the item.'), (False, 'No, platforms should not reduce exposure to the item.')], default=False)),
                ('judgment_inform', models.BooleanField(choices=[(True, 'Yes, platforms should inform users that the item may be misleading.'), (False, 'No, platforms should not inform users that the item may be misleading.')], default=False)),
                ('judgment_additional_information', models.TextField(blank=True, null=True)),
                ('misinformation_harm', models.PositiveIntegerField(verbose_name='How much harm would there be if people were misinformed about the topic of this item?')),
                ('predict_a', models.IntegerField(default=0)),
                ('predict_b', models.IntegerField(default=0)),
                ('predict_c', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Item')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Rater')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow')),
            ],
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='labeling_hit_duration',
            field=models.CharField(choices=[('2', 'Up to 2 minutes'), ('6', 'Up to 6 minutes'), ('15', 'Up to 15 minutes')], default=False, max_length=5, verbose_name='About how long should you take, on average, to complete a labeling HIT?'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='pay_attention_to_others_on_judgment',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Not sure')], default=False, max_length=1, verbose_name='In the “Judgments” section of the form, should you take into account what you think other labelers are likely tosay about an item?'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='pay_attention_to_others_on_prediction',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Not sure')], default=False, max_length=1, verbose_name='In the “Predictions” section of the form, should you take into account what you think other labelers are likely to say about an item?'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
