# Generated by Django 2.2.4 on 2019-12-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0034_auto_20191202_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelinganswer',
            name='take_action',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
