# Generated by Django 2.2.4 on 2019-12-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0035_labelinganswer_take_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemworkflow',
            name='hit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='evidence',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='judgment',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='judgment_additional_information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='misinformation_harm',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1, verbose_name='How much harm would there be if people were misinformed about the topic of this item?'),
        ),
    ]
