# Generated by Django 2.2.4 on 2019-12-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_auto_20191203_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemworkflow',
            name='raters_actual',
        ),
        migrations.RemoveField(
            model_name='itemworkflow',
            name='raters_desired',
        ),
    ]
