# Generated by Django 2.2.4 on 2019-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_auto_20191203_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemworkflow',
            old_name='hit',
            new_name='hit_group_url',
        ),
        migrations.AddField(
            model_name='itemworkflow',
            name='hit_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemworkflow',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
