# Generated by Django 2.2.4 on 2019-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0038_auto_20191203_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='corroboratingchoices',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judgmentrequirementchoices',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reducenumberofpeoplechoices',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
