# Generated by Django 2.2.4 on 2019-12-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_auto_20191205_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corroboratingchoices',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='judgmentrequirementchoices',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='reducenumberofpeoplechoices',
            name='workflow',
        ),
    ]
