# Generated by Django 2.2.4 on 2019-12-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0041_auto_20191205_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgmentrequirementchoices',
            name='correct_for_workflows',
            field=models.ManyToManyField(to='workflow.Workflow'),
        ),
    ]
