# Generated by Django 2.2.4 on 2019-12-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_judgmentrequirementchoices_correct_for_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarnPeopleChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='remove_item',
            field=models.ManyToManyField(related_name='remove_answers', to='workflow.RemoveChoices', verbose_name='Which of the following are actions that would be taken if a search engine or social media platform decided to “remove” an item?'),
        ),
        migrations.AlterField(
            model_name='registrationanswer',
            name='warn_people',
            field=models.ManyToManyField(related_name='warn_answers', to='workflow.WarnPeopleChoices', verbose_name='Which of the following are actions that would be taken if a search engine or social media platform decided to “warn” people?'),
        ),
    ]
