# Generated by Django 2.2.4 on 2019-12-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0043_auto_20191205_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicsAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=255)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Rater')),
            ],
        ),
    ]
