# Generated by Django 2.2.4 on 2020-01-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0046_auto_20191212_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rater',
            name='qualification',
            field=models.CharField(choices=[('CSMR-Labeling-1', 'CSMR-Labeling-1'), ('CSMR-Labeling-2', 'CSMR-Labeling-2'), ('CSMR-Labeling-3', 'CSMR-Labeling-3')], max_length=255),
        ),
    ]
