# Generated by Django 2.2.4 on 2020-01-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0047_auto_20200110_1718'),
        ('workflow', '0047_auto_20200110_1632'),
    ]

    operations = [
    ]
