# Generated by Django 2.2.4 on 2020-01-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0049_auto_20200113_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicsanswer',
            name='polaf_other',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Specify something else'),
        ),
        migrations.AddField(
            model_name='demographicsanswer',
            name='polid_other',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Specify something else'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='polaf',
            field=models.CharField(choices=[('1', 'A Strong Democrat'), ('2', 'A Not Very Strong Democrat'), ('3', 'Independent, lean toward Democrat'), ('4', 'Independent (close to neither party)'), ('5', 'Independent, lean toward Republican'), ('6', 'A Not Very Strong Republican'), ('7', 'Strong Republican'), ('_', 'Something else, please specify')], default=False, max_length=5, verbose_name='Generally speaking, when it comes to political parties in the United States, how would you best describe yourself?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='polid',
            field=models.CharField(choices=[('1', 'Very Liberal'), ('2', 'Liberal'), ('3', 'Somewhat Liberal'), ('4', 'Moderate or Middle of the Road'), ('5', 'Somewhat Conservative'), ('6', 'Conservative'), ('7', 'Very Conservative'), ('_', 'Something else, please specify')], default=False, max_length=5, verbose_name='Now when thinking about politics, how would you describe your political views?'),
        ),
    ]
