# Generated by Django 2.2.4 on 2020-01-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0049_auto_20200113_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='api_id',
        ),
    ]
