# Generated by Django 2.2.4 on 2020-01-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0050_auto_20200114_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicsanswer',
            name='age',
            field=models.CharField(blank=True, choices=[('< 18', 'Under 18 years old'), ('18-29', '18-29 years old'), ('30-39', '30-39 years old'), ('40-49', '40-49 years old'), ('50-59', '50-59 years old'), ('> 60', '60 years or older')], max_length=5, null=True, verbose_name='What is your age?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='crt1_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The ages of Mark and Adam add up to 28 years total. Mark is 20 years older than Adam. How many years old is Adam?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='crt1_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='If it takes 10 seconds for 10 printers to print out 10 pages of paper, how many seconds will it take 50 printers to print out 50 pages of paper?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='crt1_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='On a loaf of bread, there is a patch of mold. Every day, the patch doubles in size. If it takes 40 days for the patch to cover the entire loaf of bread, how many days would it take for the patch to cover half of the loaf of bread?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='crt3_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='If you’re running a race and you pass the person in second place, what place are you in?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='crt3_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='A farmer had 15 sheep and all but 8 died. How many are left?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='crt3_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emily’s father has three daughters. The first two are named April and May. What is the third daughter’s name?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='crt3_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='How many cubic feet of dirt are there in a hole that is 3’ deep x 3’ wide x 3’ long?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='ecoid',
            field=models.CharField(blank=True, choices=[('1', 'Very Liberal'), ('2', 'Liberal'), ('3', 'Somewhat Liberal'), ('4', 'Moderate or Middle of the Road'), ('5', 'Somewhat Conservative'), ('6', 'Conservative'), ('7', 'Very Conservative')], max_length=5, null=True, verbose_name='Now when thinking about economic issues, how would you describe your political views?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='education',
            field=models.CharField(blank=True, choices=[('1', 'Less than high school degree'), ('2', 'High school degree or equivalent (e.g., GED)'), ('3', 'Some college but no degree'), ('4', 'Associate degree'), ('5', 'Bachelor degree'), ('6', 'Graduate degree')], max_length=5, null=True, verbose_name='What is the highest level of school you have completed or the highest degree you have received?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male'), ('3', 'Non-binary / third gender'), ('_', 'Prefer to self-describe'), ('x', 'Prefer not to say')], max_length=5, null=True, verbose_name='What is your gender?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='pk_1',
            field=models.CharField(blank=True, choices=[('1', 'The President'), ('2', 'Congress'), ('3', 'The Supreme Court')], max_length=5, null=True, verbose_name='Whose responsibility is it to decide if a law is constitutional or not?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='pk_2',
            field=models.CharField(blank=True, choices=[('1', 'The President'), ('2', 'Congress'), ('3', 'The Supreme Court')], max_length=5, null=True, verbose_name='Whose responsibility is it to nominate judges to Federal Courts?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='pk_3',
            field=models.CharField(blank=True, choices=[('1', 'Theresa May'), ('2', 'Jeremy Corbyn'), ('3', 'Tony Hayward'), ('4', 'Boris Johnson')], max_length=5, null=True, verbose_name='Who is the leader of the Labour Party of Great Britain? Is it:'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='pk_4',
            field=models.CharField(blank=True, choices=[('1', 'Speaker of the House'), ('2', 'Treasury Secretary'), ('3', 'Senate Majority Leader'), ('4', 'Justice of the Supreme Court'), ('5', 'Governor of New Mexico')], max_length=5, null=True, verbose_name='Do you know what job or political office is currently held by Nancy Pelosi? Is it:'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='polaf',
            field=models.CharField(blank=True, choices=[('1', 'A Strong Democrat'), ('2', 'A Not Very Strong Democrat'), ('3', 'Independent, lean toward Democrat'), ('4', 'Independent (close to neither party)'), ('5', 'Independent, lean toward Republican'), ('6', 'A Not Very Strong Republican'), ('7', 'Strong Republican'), ('_', 'Something else, please specify')], max_length=5, null=True, verbose_name='Generally speaking, when it comes to political parties in the United States, how would you best describe yourself?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='polid',
            field=models.CharField(blank=True, choices=[('1', 'Very Liberal'), ('2', 'Liberal'), ('3', 'Somewhat Liberal'), ('4', 'Moderate or Middle of the Road'), ('5', 'Somewhat Conservative'), ('6', 'Conservative'), ('7', 'Very Conservative'), ('_', 'Something else, please specify')], max_length=5, null=True, verbose_name='Now when thinking about politics, how would you describe your political views?'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='polint',
            field=models.CharField(blank=True, choices=[('1', 'most of the time'), ('2', 'some of the time'), ('3', 'only now and then'), ('4', 'hardly at all')], max_length=5, null=True, verbose_name='Would you say you follow what’s going on in government and public affairs:'),
        ),
        migrations.AlterField(
            model_name='demographicsanswer',
            name='socid',
            field=models.CharField(blank=True, choices=[('1', 'Very Liberal'), ('2', 'Liberal'), ('3', 'Somewhat Liberal'), ('4', 'Moderate or Middle of the Road'), ('5', 'Somewhat Conservative'), ('6', 'Conservative'), ('7', 'Very Conservative')], max_length=5, null=True, verbose_name='Now when thinking about social issues, how would you describe your political views?'),
        ),
    ]
