# Generated by Django 2.2.4 on 2020-01-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0051_auto_20200114_1852'),
        ('workflow', '0050_remove_rater_api_id'),
    ]

    operations = [
    ]
