# Generated by Django 2.2.4 on 2020-01-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0054_auto_20200123_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='rater_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
