# Generated by Django 2.2.4 on 2020-01-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0055_rater_rater_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographicsanswer',
            name='pk_1',
        ),
        migrations.RemoveField(
            model_name='demographicsanswer',
            name='pk_2',
        ),
        migrations.RemoveField(
            model_name='demographicsanswer',
            name='pk_3',
        ),
        migrations.RemoveField(
            model_name='demographicsanswer',
            name='pk_4',
        ),
        migrations.RemoveField(
            model_name='registrationanswer',
            name='consent',
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='evidence',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='KnowledgeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_1', models.CharField(blank=True, choices=[('1', 'The President'), ('2', 'Congress'), ('3', 'The Supreme Court')], max_length=5, null=True, verbose_name='Whose responsibility is it to decide if a law is constitutional or not?')),
                ('pk_2', models.CharField(blank=True, choices=[('1', 'The President'), ('2', 'Congress'), ('3', 'The Supreme Court')], max_length=5, null=True, verbose_name='Whose responsibility is it to nominate judges to Federal Courts?')),
                ('pk_3', models.CharField(blank=True, choices=[('1', 'Theresa May'), ('2', 'Jeremy Corbyn'), ('3', 'Tony Hayward'), ('4', 'Boris Johnson')], max_length=5, null=True, verbose_name='Who is the leader of the Labour Party of Great Britain? Is it:')),
                ('pk_4', models.CharField(blank=True, choices=[('1', 'Speaker of the House'), ('2', 'Treasury Secretary'), ('3', 'Senate Majority Leader'), ('4', 'Justice of the Supreme Court'), ('5', 'Governor of New Mexico')], max_length=5, null=True, verbose_name='Do you know what job or political office is currently held by Nancy Pelosi? Is it:')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Rater')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.CharField(choices=[('y', 'Yes, I consent to participate in this study'), ('n', 'No, I do not consent to participate in this study')], default=False, max_length=5, verbose_name='This is a research study at the University of Michigan. Please view the <a href="https://drive.google.com/file/d/14S-hc5mcXP0BfGDymJcGAmCW1nG6quUW/view?usp=sharing" target="_blank">contest form</a>, read it, and then indicate whether you consent to participate in the study, by clicking below.')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Rater')),
            ],
        ),
    ]
