# Generated by Django 2.2.4 on 2020-01-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0056_auto_20200131_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationAnswer',
            new_name='QuizAnswer',
        ),
    ]
