# Generated by Django 2.2.4 on 2020-02-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0057_auto_20200201_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='take_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
