# Generated by Django 2.2.4 on 2020-02-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0057_auto_20200131_1712'),
        ('workflow', '0060_auto_20200201_0247'),
    ]

    operations = [
    ]
