# Generated by Django 2.2.10 on 2020-02-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0062_auto_20200201_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemworkflow',
            name='prev_urls',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='consentanswer',
            name='consent',
            field=models.CharField(choices=[('y', 'Yes, I consent to participate in this study'), ('n', 'No, I do not consent to participate in this study')], default=False, max_length=5, verbose_name='This is a research study at the University of Michigan. Please view the <a href="https://drive.google.com/file/d/14S-hc5mcXP0BfGDymJcGAmCW1nG6quUW/view?usp=sharing" target="_blank">consent form</a>, read it, and then indicate whether you consent to participate in the study, by clicking below.'),
        ),
        migrations.AlterField(
            model_name='knowledgeanswer',
            name='pk_4',
            field=models.CharField(blank=True, choices=[('1', 'Speaker of the House'), ('2', 'Treasury Secretary'), ('3', 'Senate Majority Leader'), ('4', 'Justice of the Supreme Court'), ('5', 'Governor of New Mexico')], max_length=5, null=True, verbose_name='What job or political office is currently held by Nancy Pelosi? Is it:'),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='misinformation_harm',
            field=models.PositiveIntegerField(choices=[(1, '1 = No harm at all'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7 = Extremely harmful')], default=None, verbose_name='How much harm would there be if people were misinformed about the topic of this item?'),
        ),
    ]
