# Generated by Django 2.2.10 on 2020-02-04 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0063_auto_20200203_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemworkflow',
            name='prev_urls',
        ),
        migrations.CreateModel(
            name='ItemURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_urls', models.CharField(blank=True, max_length=2000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Item')),
            ],
        ),
    ]
