# Generated by Django 2.2.10 on 2020-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0064_auto_20200204_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='evidence_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
