# Generated by Django 2.2.10 on 2020-02-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0066_auto_20200205_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='predict_a',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='predict_any',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='predict_b',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='predict_c',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
