# Generated by Django 2.2.10 on 2020-02-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0068_auto_20200205_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='judgment_misleading_item',
            field=models.PositiveIntegerField(blank=True, choices=[('1', '1 = not misleading at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7 = false or extremely misleading')], default=None, null=True, verbose_name='Taking into account any evidence you found, how misleading is this item?'),
        ),
    ]
