# Generated by Django 2.2.10 on 2020-02-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0070_auto_20200207_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='labeling_hit_duration',
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='judgment_inform',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes, if the item is not removed, platforms should inform users that it may be misleading.'), (False, 'No, platforms should not inform users that the item may be misleading.')], default=None, null=True, verbose_name='3. <b>Inform</b> users that the item may be misleading. (Assuming it is not removed.)'),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='judgment_misleading_item',
            field=models.PositiveIntegerField(blank=True, choices=[(None, ''), (1, '1 = not misleading at all'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7 = false or extremely misleading')], default=None, null=True, verbose_name='How misleading is this item?'),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='judgment_reduce',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes, if the item is not removed, platforms should reduce exposure to the item.'), (False, 'No, platforms should not reduce exposure to the item.')], default=None, null=True, verbose_name='2. <b>Reduce</b> the item’s audience. (Assuming it is not removed.)'),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='take_action',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes, one or more of these actions should be taken.'), (False, 'No, none of these actions should be taken.')], default=None, null=True, verbose_name='\n            Based on your answers to the last two questions \n            (misinformation and harm), in your personal opinion do you think \n            that social media platforms and search engines should take \n            <b>any of the following actions</b> on this item?\n            <br></br>\n            <ul>\n                <li><b>Remove</b> the item.  \n                    <br>For example, Google would not present this item in \n                    search results. Facebook and Twitter would not present \n                    posts that link to this item anywhere.</li>\n                <li>If it is not removed, <b>reduce</b> the item’s audience.                      \n                    <br>For example, Google would present the item on the \n                    second page of search results, and Facebook and Twitter \n                    would present it where people have to scroll more before \n                    they see it. That way, fewer people would see it, but some\n                     people still would.</li>                    \n                <li>If it is not removed, <b>inform</b> users that the item may be misleading, \n                    <br>For example, there might be a “misleading” \n                    icon next to the item that users could click on to find out\n                     more information about why it is marked as misleading.</li>                    \n            </ul>\n        '),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='judgment_requirements',
            field=models.ManyToManyField(blank=True, to='workflow.JudgmentRequirementChoices', verbose_name='What do we expect you to do before entering your judgments?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='pay_attention_to_others_on_judgment',
            field=models.CharField(blank=True, choices=[('self', 'My personal opinion about what search engines and social media platforms should do'), ('others', 'What I think others will say the search engines and social media platforms should do'), ('NoTB', 'Neither of these')], default=False, max_length=255, null=True, verbose_name='In the “Personal Judgment Questions” section of the form, which should you report?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='pay_attention_to_others_on_prediction',
            field=models.CharField(blank=True, choices=[('self', 'My personal opinion about what search engines and social media platforms should do'), ('others', 'What I think others will say the search engines and social media platforms should do'), ('NoTB', 'Neither of these')], default=False, max_length=255, null=True, verbose_name='In the “Prediction Questions” section of the form, which should you do?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='reduce_number_of_people',
            field=models.ManyToManyField(blank=True, related_name='reduced_answers', to='workflow.ReduceNumberOfPeopleChoices', verbose_name='As we described it, what does <b>reduce</b> mean?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='remove_item',
            field=models.ManyToManyField(blank=True, related_name='remove_answers', to='workflow.RemoveChoices', verbose_name='As we described it, what does <b>remove</b> mean?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='warn_people',
            field=models.ManyToManyField(blank=True, related_name='warn_answers', to='workflow.WarnPeopleChoices', verbose_name='As we described it, what does <b>inform</b> mean?'),
        ),
    ]
