# Generated by Django 2.2.10 on 2020-02-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0071_auto_20200209_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelinganswer',
            old_name='predict_c',
            new_name='predict_inform',
        ),
        migrations.RenameField(
            model_name='labelinganswer',
            old_name='predict_b',
            new_name='predict_reduce',
        ),
        migrations.RenameField(
            model_name='labelinganswer',
            old_name='predict_a',
            new_name='predict_remove',
        ),
    ]
