# Generated by Django 2.2.10 on 2020-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0073_auto_20200210_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='corroborating_link_clicked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='item_link_clicked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='take_action',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes, one or more of these actions should be taken.'), (False, 'No, none of these actions should be taken.')], default=None, null=True, verbose_name='\n            Based on your answers to the last two questions \n            (misinformation and harm), in your personal opinion do you think \n            that social media platforms and search engines should take \n            <b>any of the following actions</b> on this item?\n            <br></br>\n            <ul>\n                <li><b>Remove</b> the item.  \n                    <br>For example, Google would not present this item in \n                    search results. Facebook and Twitter would not present \n                    posts that link to this item anywhere.</li>\n                <li>If it is not removed, <b>reduce</b> the item’s audience.\n                    <br>For example, Google would present the item on the \n                    second page of search results, and Facebook and Twitter \n                    would present it where people have to scroll more before \n                    they see it. That way, fewer people would see it, but some\n                     people still would.</li>                    \n                <li>If it is not removed, <b>inform</b> users that the item may\n                    be misleading, \n                    <br>For example, there might be a “misleading” \n                    icon next to the item that users could click on to find out\n                     more information about why it is marked as misleading.</li>\n            </ul>\n        '),
        ),
    ]
