# Generated by Django 2.2.10 on 2020-02-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0074_auto_20200211_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='first_failed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
