# Generated by Django 2.2.10 on 2020-02-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0075_quizanswer_first_failed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswer',
            old_name='first_failed',
            new_name='second_attempt',
        ),
    ]
