# Generated by Django 2.2.10 on 2020-02-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0076_auto_20200212_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
