# Generated by Django 2.2.10 on 2020-02-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0077_quizanswer_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswer',
            old_name='warn_people',
            new_name='inform',
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='reduce_number_of_people',
            new_name='reduce',
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='remove_item',
            new_name='remove',
        ),
    ]
