# Generated by Django 2.2.10 on 2020-02-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0078_auto_20200212_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='inform',
            field=models.ManyToManyField(blank=True, related_name='inform_answers', to='workflow.WarnPeopleChoices', verbose_name='As we described it, what does <b>inform</b> mean?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='reduce',
            field=models.ManyToManyField(blank=True, related_name='reduce_answers', to='workflow.ReduceNumberOfPeopleChoices', verbose_name='As we described it, what does <b>reduce</b> mean?'),
        ),
    ]
