# Generated by Django 2.2.10 on 2020-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0080_auto_20200213_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='take_action',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes, one or more of these actions should be taken.'), (False, 'No, none of these actions should be taken.')], default=None, null=True, verbose_name='\n            \n            There are three possible actions.\n            <ul>\n                <li><b>Inform users</b>.\n                    <br><i>Show a "misleading" icon next to the item.</i></br>\n                </li>\n                <li><b>Reduce</b> the item’s audience.\n                    <br><i>Show the item on the second page of Google search results, and lower in Facebook and Twitter feeds.</i></br>\n                </li>\n                <li><b>Remove</b> the item. \n                    <br><i>Don’t show the item at all in Google search results or Facebook and Twitter feeds.</i></br>\n                </li>\n            </ul>\n            Based on your answers to the last two questions \n            (misinformation and harm), in your personal opinion do you think \n            that social media platforms and search engines should take \n            <b>at least one of these actions</b> on this item?\n        '),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='pay_attention_to_others_on_judgment',
            field=models.CharField(blank=True, choices=[('self', 'My personal opinion about what search engines and social media platforms should do'), ('others', 'What I think others will say the search engines and social media platforms should do'), ('NoTB', 'Neither of these')], default=False, max_length=255, null=True, verbose_name='In the "Action Questions" section of the form, which should you report?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='pay_attention_to_others_on_prediction',
            field=models.CharField(blank=True, choices=[('self', 'My personal opinion about what search engines and social media platforms should do'), ('others', 'What I think others will say the search engines and social media platforms should do'), ('NoTB', 'Neither of these')], default=False, max_length=255, null=True, verbose_name='In the "Prediction Questions" section of the form, which should you do?'),
        ),
    ]
