# Generated by Django 2.2.10 on 2020-02-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0081_auto_20200213_2153'),
        ('workflow', '0082_auto_20200213_1819'),
    ]

    operations = [
    ]
