# Generated by Django 2.2.10 on 2020-02-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0083_merge_20200213_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswer',
            old_name='corroborating_link',
            new_name='corroborating_link_meaning',
        ),
    ]
