# Generated by Django 2.2.10 on 2020-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0084_auto_20200215_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='evidence',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Second, take <b>up to five minutes</b> to search to find evidence that will help you judge the news item.<br>You should look for both <b>supporting and challenging</b> evidence.</br><br>Did you find any page with evidence you found convincing?</br>'),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='judgment',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Do you know enough about the news item to judge it?'),
        ),
    ]
