# Generated by Django 2.2.10 on 2020-02-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0086_auto_20200217_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='evidence',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='Second, take <b>up to five minutes</b> to search to find evidence that will help you judge the news item.<br>You should look for both <b>supporting and challenging</b> evidence.</br><br>Did you find any page with evidence you found convincing?</br>'),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='judgment_misleading_item',
            field=models.PositiveIntegerField(blank=True, choices=[(None, ''), (1, '1 = not misleading at all'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7 = false or extremely misleading'), (0, "I don't have enough information to make a judgment")], default=None, null=True, verbose_name='How misleading is this news item?'),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='misinformation_harm',
            field=models.PositiveIntegerField(blank=True, choices=[(None, ''), (1, '1 = No harm at all'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7 = Extremely harmful')], default=None, null=True, verbose_name='How much harm would there be if people were misinformed about the topic of this news item?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='corroborating_link_meaning',
            field=models.ManyToManyField(blank=True, to='workflow.CorroboratingChoices', verbose_name='Which of the following are you supposed to enter in the field for an evidence link?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='judgment_requirements',
            field=models.ManyToManyField(blank=True, to='workflow.JudgmentRequirementChoices', verbose_name='What do we expect you to do before answering the assessment questions'),
        ),
    ]
