# Generated by Django 2.2.10 on 2020-02-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0087_auto_20200218_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='ab_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
