# Generated by Django 2.2.10 on 2020-02-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0088_rater_ab_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='inform_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reduce_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='remove_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_simulated_answers',
        ),
        migrations.CreateModel(
            name='ItemAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform_count', models.IntegerField(blank=True, null=True)),
                ('reduce_count', models.IntegerField(blank=True, null=True)),
                ('remove_count', models.IntegerField(blank=True, null=True)),
                ('total_simulated_answers', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Item')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow')),
            ],
        ),
    ]
