# Generated by Django 2.2.10 on 2020-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0089_auto_20200219_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemanswers',
            options={'verbose_name_plural': 'Item answers'},
        ),
        migrations.AddField(
            model_name='itemanswers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemurls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
