# Generated by Django 2.2.10 on 2020-02-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0094_corroboratingchoices_correct_for_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectLinkClicked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_link_clicked', models.BooleanField(blank=True, default=False, null=True)),
                ('corroborating_link_clicked', models.BooleanField(blank=True, default=False, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Item')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Rater')),
            ],
        ),
    ]
