# Generated by Django 2.2.10 on 2020-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0095_redirectlinkclicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelinganswer',
            name='evidence_search_terms',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='What search terms worked best for you?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='corroborating_link_meaning',
            field=models.ManyToManyField(blank=True, to='workflow.CorroboratingChoices', verbose_name='Suppose that you <b>searched on Google</b> for "Cupping treatment cancer", and that you found convincing evidence at https://www.cancer.gov/about-cancer/. <b>What should you have pasted as an evidence link</b> in the form above?<br><b>(Check all that apply)</b></br>'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='inform',
            field=models.ManyToManyField(blank=True, related_name='inform_answers', to='workflow.InformChoices', verbose_name='As we described it, what does <b>inform</b> mean?<br><b>(Check all that apply)</b></br>'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='judgment_requirements',
            field=models.ManyToManyField(blank=True, to='workflow.JudgmentRequirementChoices', verbose_name='What do we expect you to do before answering the assessment questions?<br><b>(Check all that apply)</b></br>'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='pay_attention_to_others_on_prediction',
            field=models.CharField(blank=True, choices=[('self', 'My personal opinion about what search engines and social media platforms should do'), ('others', 'What I think others will say the search engines and social media platforms should do'), ('NoTB', 'Neither of these')], default=False, max_length=255, null=True, verbose_name='In the "Prediction Questions" section of the form, which should you report?'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='reduce',
            field=models.ManyToManyField(blank=True, related_name='reduce_answers', to='workflow.ReduceChoices', verbose_name='As we described it, what does <b>reduce</b> mean?<br><b>(Check all that apply)</b></br>'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='remove',
            field=models.ManyToManyField(blank=True, related_name='remove_answers', to='workflow.RemoveChoices', verbose_name='As we described it, what does <b>remove</b> mean?<br><b>(Check all that apply)</b></br>'),
        ),
    ]
