# Generated by Django 2.2.10 on 2020-03-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0096_auto_20200301_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='evidence',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, null=True, verbose_name='<br>Did you find any page with evidence you found convincing, one way or the other?</br>'),
        ),
        migrations.AlterField(
            model_name='labelinganswer',
            name='evidence_search_terms',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='What search terms did you use?'),
        ),
    ]
