# Generated by Django 2.2.10 on 2020-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0097_auto_20200303_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='take_action',
            field=models.CharField(choices=[('Yes', 'Yes, one or more of these actions should be taken.'), ('No', 'No, none of these actions should be taken.'), ('Not enough info', "I don't have enough information to judge")], default=None, max_length=32, null=True, verbose_name='\n            Based on your answers to the last two questions \n            (misinformation and harm), in your personal opinion do you think \n            that social media platforms and search engines should take \n            <b>at least one of these actions</b> on this item?\n        '),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.CharField(choices=[('WITHOUT_EVIDENCE_URL_WORKFLOW', 'Workflow without evidence'), ('EVIDENCE_URL_INPUT_WORKFLOW', 'Evidence url based workflow'), ('EVIDENCE_URLS_JUDGMENT_WORKFLOW', 'Evidence based judgment workflow'), ('JOURNALIST_WORKFLOW', 'Journalist workflow')], default='WITHOUT_EVIDENCE_URL_WORKFLOW', max_length=255),
        ),
    ]
