# Generated by Django 2.2.10 on 2020-06-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0098_auto_20200511_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinganswer',
            name='take_action',
            field=models.CharField(choices=[('Yes', 'Yes, one or more of these actions should be taken.'), ('No', 'No, none of these actions should be taken.'), ('Not enough info', "I don't have enough information to judge")], default=None, max_length=32, null=True, verbose_name='\n            Based on your answers to the last two questions\n            (misinformation and harm), in your personal opinion do you think\n            that social media platforms and search engines should take\n            <b>at least one of these actions</b> on this item?\n        '),
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(blank=True, choices=[('Uncivil', 'Uncivil: The comment criticizes other people or their ideas in insulting ways, argues that people who disagree with them should suffer, or tells them to stop expressing opinions.'), ('Civil', 'Civil: The comment is not uncivil – it takes a stance, even a strong one, without attacking people who disagree or arguing that they should stop talking.')], default=None, max_length=10, null=True, verbose_name='Of course I hope he suffers. He not only hates gay men, but he targets LGBT children, who already have a high rate of homelessness and mental health issues caused by stress. He supports “conversion therapy,” a form of torture. He would allow local grocery stores and restaurants to refuse to serve an LGBT person, which would disproportionately impact rural LGBT youth. If there were a way to knock some empathy into him, I wish someone would do it. Why am I supposed to want to protect someone who seeks to hurt us?')),
                ('select1', models.CharField(blank=True, choices=[('Uncivil', 'Uncivil: The comment criticizes other people or their ideas in insulting ways, argues that people who disagree with them should suffer, or tells them to stop expressing opinions.'), ('Civil', 'Civil: The comment is not uncivil – it takes a stance, even a strong one, without attacking people who disagree or arguing that they should stop talking.')], default=None, max_length=10, null=True, verbose_name='XXXXXXX2?')),
                ('select2', models.CharField(blank=True, choices=[('Uncivil', 'Uncivil: The comment criticizes other people or their ideas in insulting ways, argues that people who disagree with them should suffer, or tells them to stop expressing opinions.'), ('Civil', 'Civil: The comment is not uncivil – it takes a stance, even a strong one, without attacking people who disagree or arguing that they should stop talking.')], default=None, max_length=10, null=True, verbose_name='XXXXXXX3333?')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Rater')),
            ],
        ),
    ]
