# Generated by Django 2.2.10 on 2020-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0100_auto_20200708_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
